use_frameworks!

platform :ios, '8.0'

inhibit_all_warnings!

target 'EasyCalls-Example' do
    
    pod 'EasyCalls/Alert', :path => '../'
    pod 'EasyCalls/TryCatch', :path => '../'
    pod 'EasyCalls/Queues', :path => '../'
end

target 'EasyCalls_Tests' do

  pod 'EasyCalls', :path => '../'
  pod 'EasyCalls/Realm', :path => '../'
  
  #TEST
  pod 'Quick', '~> 1.2.0'
  pod 'Nimble', '~> 7.0.2'
end
