# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode9.2
language: swift

# cache: cocoapods
podfile: Example/Podfile

before_install:
- gem install cocoapods # Since Travis is not always on latest version
- cd Example
- pod update
- pod install
script:

- xcodebuild test -workspace 'EasyCalls.xcworkspace' -scheme EasyCalls-Test -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 8,OS=11.2' ONLY_ACTIVE_ARCH=NO
- cd ..
- pod lib lint --allow-warnings

after_success:
- bash <(curl -s https://codecov.io/bash)